# Generated by Django 5.0.10 on 2025-01-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_need_update_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_password_last_updated",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date password last updated"
            ),
        ),
    ]
